### ISSUE TITLE
Undefined class constant 'FETCH_KEY_PAIR'

### ISSUE THREAD

**Issue by savchuks** [phalcon/cphalcon#10266]
Hi!
Working code started return - Fatal error : Undefined class constant 'FETCH_KEY_PAIR'.
I cannot figure out, why its happens, before it works ok.
If i choose some other constant, like FETCH_ASSOC or FETCH_OBJ - it works, but \Phalcon\Db::FETCH_KEY_PAIR does not work, why it can be, maybe i need any updates ?

Phalcon version 2.0.0

**Comment by andresgutierrez** [comment]
This is fixed in the 2.0.x branch, could you please try again?

**Comment by savchuks** [comment]
Thanks, Fix #10266 helped me. I've just manually updated db.zep and recompile it

**Comment by savchuks** [comment]
I got latest version Phalcon 2.0.6 from git://github.com/phalcon/cphalcon.git
My PHP Version 5.6.11, and MYSQL API library version is 5.5.44

Still when try to use FETCH_KEY_PAIR i get error "SQLSTATE[HY000]: General error: fetch mode doesn't allow any extra arguments".
I cannot figure out what else i need to update to make it work ?

**Comment by andresgutierrez** [comment]
I've added another fix

**Comment by savchuks** [comment]
I've updated Phalcon version to 2.0.7 
Still get the same error when try to use fetchAll with FETCH_KEY_PAIR argument.

**Comment by Green-Cat** [comment]
@savchuks could you check with 2.0.8 (the current 2.0.x branch), as that's where the aforementioned patch landed.
