### ISSUE TITLE
[2.0.x] Segfault in Application (Happening more frequently this past few days)

### ISSUE THREAD

**Issue by virgofx** [phalcon/cphalcon#10301]
* Vagrant, Linux Centos 7
* PHP 5.6, php-fpm
* Nginx 1.9.0

```
Program received signal SIGSEGV, Segmentation fault.
0x00007fcbd0d167a1 in _zend_mm_free_int ()
(gdb) bt
#0  0x00007fcbd0d167a1 in _zend_mm_free_int ()
#1  0x00007fcbbdabd16d in phannot_internal_parse_annotations.isra.98 () from /usr/lib64/php/modules/phalcon.so
#2  0x00007fcbbdc976ad in zim_Phalcon_Annotations_Reader_parse () from /usr/lib64/php/modules/phalcon.so
#3  0x00007fcbd0d2f02b in dtrace_execute_internal ()
#4  0x00007fcbc6374936 in xdebug_execute_internal (current_execute_data=0x7fffedcbda90, fci=0x7fffedcbdc00, return_value_used=1) at /tmp/xdebug-2.2.5/xdebug.c:1551
#5  0x00007fcbbdaaa750 in zephir_call_function_opt () from /usr/lib64/php/modules/phalcon.so
#6  0x00007fcbbdad860f in zephir_call_user_function () from /usr/lib64/php/modules/phalcon.so
#7  0x00007fcbbdad8844 in zephir_call_class_method_aparams () from /usr/lib64/php/modules/phalcon.so
#8  0x00007fcbbdb5bf49 in zim_Phalcon_Annotations_Adapter_get () from /usr/lib64/php/modules/phalcon.so
#9  0x00007fcbd0d2f02b in dtrace_execute_internal ()
#10 0x00007fcbc6374936 in xdebug_execute_internal (current_execute_data=0x7fcbd0a8ebb0, fci=0x0, return_value_used=1) at /tmp/xdebug-2.2.5/xdebug.c:1551
#11 0x00007fcbd0de8f68 in zend_do_fcall_common_helper_SPEC ()
#12 0x00007fcbd0d7d198 in execute_ex ()
#13 0x00007fcbd0d2ef09 in dtrace_execute_ex ()
#14 0x00007fcbc6373ebc in xdebug_execute_ex (execute_data=0x7fcbd0a8ebb0) at /tmp/xdebug-2.2.5/xdebug.c:1437
#15 0x00007fcbbdaaa04b in zephir_call_function_opt () from /usr/lib64/php/modules/phalcon.so
#16 0x00007fcbbdad860f in zephir_call_user_function () from /usr/lib64/php/modules/phalcon.so
#17 0x00007fcbbdad8844 in zephir_call_class_method_aparams () from /usr/lib64/php/modules/phalcon.so
#18 0x00007fcbbdd66f0c in zim_Phalcon_Events_Manager_fireQueue () from /usr/lib64/php/modules/phalcon.so
#19 0x00007fcbd0d2f02b in dtrace_execute_internal ()
#20 0x00007fcbc6374936 in xdebug_execute_internal (current_execute_data=0x7fffedcbec60, fci=0x7fffedcbedd0, return_value_used=1) at /tmp/xdebug-2.2.5/xdebug.c:1551
#21 0x00007fcbbdaaa750 in zephir_call_function_opt () from /usr/lib64/php/modules/phalcon.so
#22 0x00007fcbbdad860f in zephir_call_user_function () from /usr/lib64/php/modules/phalcon.so
#23 0x00007fcbbdad8844 in zephir_call_class_method_aparams () from /usr/lib64/php/modules/phalcon.so
#24 0x00007fcbbdd65e73 in zim_Phalcon_Events_Manager_fire () from /usr/lib64/php/modules/phalcon.so
#25 0x00007fcbd0d2f02b in dtrace_execute_internal ()
#26 0x00007fcbc6374936 in xdebug_execute_internal (current_execute_data=0x7fffedcbf420, fci=0x7fffedcbf590, return_value_used=1) at /tmp/xdebug-2.2.5/xdebug.c:1551
#27 0x00007fcbbdaaa750 in zephir_call_function_opt () from /usr/lib64/php/modules/phalcon.so
#28 0x00007fcbbdad860f in zephir_call_user_function () from /usr/lib64/php/modules/phalcon.so
#29 0x00007fcbbdad8844 in zephir_call_class_method_aparams () from /usr/lib64/php/modules/phalcon.so
#30 0x00007fcbbdbf28dc in zim_Phalcon_Mvc_Model_Manager_initialize () from /usr/lib64/php/modules/phalcon.so
#31 0x00007fcbd0d2f02b in dtrace_execute_internal ()
#32 0x00007fcbc6374936 in xdebug_execute_internal (current_execute_data=0x7fffedcbfb60, fci=0x7fffedcbfcd0, return_value_used=1) at /tmp/xdebug-2.2.5/xdebug.c:1551
#33 0x00007fcbbdaaa750 in zephir_call_function_opt () from /usr/lib64/php/modules/phalcon.so
#34 0x00007fcbbdad860f in zephir_call_user_function () from /usr/lib64/php/modules/phalcon.so
#35 0x00007fcbbdad8844 in zephir_call_class_method_aparams () from /usr/lib64/php/modules/phalcon.so
#36 0x00007fcbbdbdf4ad in zim_Phalcon_Mvc_Model___construct () from /usr/lib64/php/modules/phalcon.so
#37 0x00007fcbd0d2f02b in dtrace_execute_internal ()
#38 0x00007fcbc6374936 in xdebug_execute_internal (current_execute_data=0x7fffedcc0290, fci=0x7fffedcc0400, return_value_used=1) at /tmp/xdebug-2.2.5/xdebug.c:1551
#39 0x00007fcbbdaaa750 in zephir_call_function_opt () from /usr/lib64/php/modules/phalcon.so
#40 0x00007fcbbdad860f in zephir_call_user_function () from /usr/lib64/php/modules/phalcon.so
#41 0x00007fcbbdad8844 in zephir_call_class_method_aparams () from /usr/lib64/php/modules/phalcon.so
#42 0x00007fcbbdd87233 in zim_Phalcon_Mvc_Model_Manager_load () from /usr/lib64/php/modules/phalcon.so
#43 0x00007fcbd0d2f02b in dtrace_execute_internal ()
#44 0x00007fcbc6374936 in xdebug_execute_internal (current_execute_data=0x7fffedcc0a30, fci=0x7fffedcc0ba0, return_value_used=1) at /tmp/xdebug-2.2.5/xdebug.c:1551
#45 0x00007fcbbdaaa750 in zephir_call_function_opt () from /usr/lib64/php/modules/phalcon.so
#46 0x00007fcbbdad860f in zephir_call_user_function () from /usr/lib64/php/modules/phalcon.so
#47 0x00007fcbbdad8844 in zephir_call_class_method_aparams () from /usr/lib64/php/modules/phalcon.so
#48 0x00007fcbbdbfdb32 in zim_Phalcon_Mvc_Model_Query__prepareSelect () from /usr/lib64/php/modules/phalcon.so
#49 0x00007fcbd0d2f02b in dtrace_execute_internal ()
#50 0x00007fcbc6374936 in xdebug_execute_internal (current_execute_data=0x7fffedcc13d0, fci=0x7fffedcc1540, return_value_used=1) at /tmp/xdebug-2.2.5/xdebug.c:1551
#51 0x00007fcbbdaaa750 in zephir_call_function_opt () from /usr/lib64/php/modules/phalcon.so
#52 0x00007fcbbdad860f in zephir_call_user_function () from /usr/lib64/php/modules/phalcon.so
#53 0x00007fcbbdad8844 in zephir_call_class_method_aparams () from /usr/lib64/php/modules/phalcon.so
#54 0x00007fcbbdc983f4 in zim_Phalcon_Mvc_Model_Query_parse () from /usr/lib64/php/modules/phalcon.so
#55 0x00007fcbd0d2f02b in dtrace_execute_internal ()
#56 0x00007fcbc6374936 in xdebug_execute_internal (current_execute_data=0x7fffedcc1b70, fci=0x7fffedcc1ce0, return_value_used=1) at /tmp/xdebug-2.2.5/xdebug.c:1551
#57 0x00007fcbbdaaa750 in zephir_call_function_opt () from /usr/lib64/php/modules/phalcon.so
#58 0x00007fcbbdad860f in zephir_call_user_function () from /usr/lib64/php/modules/phalcon.so
#59 0x00007fcbbdad8844 in zephir_call_class_method_aparams () from /usr/lib64/php/modules/phalcon.so
#60 0x00007fcbbdbf7120 in zim_Phalcon_Mvc_Model_Query_execute () from /usr/lib64/php/modules/phalcon.so
#61 0x00007fcbd0d2f02b in dtrace_execute_internal ()
#62 0x00007fcbc6374936 in xdebug_execute_internal (current_execute_data=0x7fffedcc2370, fci=0x7fffedcc24e0, return_value_used=1) at /tmp/xdebug-2.2.5/xdebug.c:1551
#63 0x00007fcbbdaaa750 in zephir_call_function_opt () from /usr/lib64/php/modules/phalcon.so
#64 0x00007fcbbdad860f in zephir_call_user_function () from /usr/lib64/php/modules/phalcon.so
#65 0x00007fcbbdad8844 in zephir_call_class_method_aparams () from /usr/lib64/php/modules/phalcon.so
#66 0x00007fcbbdbdc22e in zim_Phalcon_Mvc_Model_findFirst () from /usr/lib64/php/modules/phalcon.so
#67 0x00007fcbd0d2f02b in dtrace_execute_internal ()
#68 0x00007fcbc6374936 in xdebug_execute_internal (current_execute_data=0x7fcbd0a8e968, fci=0x0, return_value_used=1) at /tmp/xdebug-2.2.5/xdebug.c:1551
---Type <return> to continue, or q <return> to quit---
#69 0x00007fcbd0de8f68 in zend_do_fcall_common_helper_SPEC ()
#70 0x00007fcbd0d7d198 in execute_ex ()
#71 0x00007fcbd0d2ef09 in dtrace_execute_ex ()
#72 0x00007fcbc6373ebc in xdebug_execute_ex (execute_data=0x7fcbd0a8e968) at /tmp/xdebug-2.2.5/xdebug.c:1437
#73 0x00007fcbd0d30cf3 in zend_call_function ()
#74 0x00007fcbbdaa48fd in zephir_call_user_func_array_noex () from /usr/lib64/php/modules/phalcon.so
#75 0x00007fcbbdb9fc05 in zim_Phalcon_Di_Service_resolve () from /usr/lib64/php/modules/phalcon.so
#76 0x00007fcbd0d2f02b in dtrace_execute_internal ()
#77 0x00007fcbc6374936 in xdebug_execute_internal (current_execute_data=0x7fffedcc31b0, fci=0x7fffedcc3320, return_value_used=1) at /tmp/xdebug-2.2.5/xdebug.c:1551
#78 0x00007fcbbdaaa750 in zephir_call_function_opt () from /usr/lib64/php/modules/phalcon.so
#79 0x00007fcbbdad860f in zephir_call_user_function () from /usr/lib64/php/modules/phalcon.so
#80 0x00007fcbbdad8844 in zephir_call_class_method_aparams () from /usr/lib64/php/modules/phalcon.so
#81 0x00007fcbbdb4bdb3 in zim_Phalcon_Di_get () from /usr/lib64/php/modules/phalcon.so
#82 0x00007fcbd0d2f02b in dtrace_execute_internal ()
#83 0x00007fcbc6374936 in xdebug_execute_internal (current_execute_data=0x7fffedcc3960, fci=0x7fffedcc3ad0, return_value_used=1) at /tmp/xdebug-2.2.5/xdebug.c:1551
#84 0x00007fcbbdaaa750 in zephir_call_function_opt () from /usr/lib64/php/modules/phalcon.so
#85 0x00007fcbbdad860f in zephir_call_user_function () from /usr/lib64/php/modules/phalcon.so
#86 0x00007fcbbdad8844 in zephir_call_class_method_aparams () from /usr/lib64/php/modules/phalcon.so
#87 0x00007fcbbdb4b87a in zim_Phalcon_Di_getShared () from /usr/lib64/php/modules/phalcon.so
#88 0x00007fcbd0d2f02b in dtrace_execute_internal ()
#89 0x00007fcbc6374936 in xdebug_execute_internal (current_execute_data=0x7fcbd0a8e808, fci=0x0, return_value_used=1) at /tmp/xdebug-2.2.5/xdebug.c:1551
#90 0x00007fcbd0de8f68 in zend_do_fcall_common_helper_SPEC ()
#91 0x00007fcbd0d7d198 in execute_ex ()
#92 0x00007fcbd0d2ef09 in dtrace_execute_ex ()
#93 0x00007fcbc6373ebc in xdebug_execute_ex (execute_data=0x7fcbd0a8e808) at /tmp/xdebug-2.2.5/xdebug.c:1437
#94 0x00007fcbd0de94ca in zend_do_fcall_common_helper_SPEC ()
#95 0x00007fcbd0d7d198 in execute_ex ()
#96 0x00007fcbd0d2ef09 in dtrace_execute_ex ()
#97 0x00007fcbc6373ebc in xdebug_execute_ex (execute_data=0x7fcbd0a8e6c8) at /tmp/xdebug-2.2.5/xdebug.c:1437
#98 0x00007fcbd0de94ca in zend_do_fcall_common_helper_SPEC ()
#99 0x00007fcbd0d7d198 in execute_ex ()
#100 0x00007fcbd0d2ef09 in dtrace_execute_ex ()
#101 0x00007fcbc6373ebc in xdebug_execute_ex (execute_data=0x7fcbd0a8e5b8) at /tmp/xdebug-2.2.5/xdebug.c:1437
#102 0x00007fcbbdaaa04b in zephir_call_function_opt () from /usr/lib64/php/modules/phalcon.so
#103 0x00007fcbbdad860f in zephir_call_user_function () from /usr/lib64/php/modules/phalcon.so
#104 0x00007fcbbdad8844 in zephir_call_class_method_aparams () from /usr/lib64/php/modules/phalcon.so
#105 0x00007fcbbdd4a388 in zim_Phalcon_Dispatcher_dispatch () from /usr/lib64/php/modules/phalcon.so
#106 0x00007fcbd0d2f02b in dtrace_execute_internal ()
#107 0x00007fcbc6374936 in xdebug_execute_internal (current_execute_data=0x7fffedcc4f90, fci=0x7fffedcc5100, return_value_used=1)
    at /tmp/xdebug-2.2.5/xdebug.c:1551
#108 0x00007fcbbdaaa750 in zephir_call_function_opt () from /usr/lib64/php/modules/phalcon.so
#109 0x00007fcbbdad860f in zephir_call_user_function () from /usr/lib64/php/modules/phalcon.so
#110 0x00007fcbbdad8844 in zephir_call_class_method_aparams () from /usr/lib64/php/modules/phalcon.so
#111 0x00007fcbbdbbbb59 in zim_Phalcon_Mvc_Application_handle () from /usr/lib64/php/modules/phalcon.so
#112 0x00007fcbd0d2f02b in dtrace_execute_internal ()
#113 0x00007fcbc6374936 in xdebug_execute_internal (current_execute_data=0x7fcbd0a8e410, fci=0x0, return_value_used=1) at /tmp/xdebug-2.2.5/xdebug.c:1551
#114 0x00007fcbd0de8f68 in zend_do_fcall_common_helper_SPEC ()
#115 0x00007fcbd0d7d198 in execute_ex ()
#116 0x00007fcbd0d2ef09 in dtrace_execute_ex ()
#117 0x00007fcbc6373ebc in xdebug_execute_ex (execute_data=0x7fcbd0a8e410) at /tmp/xdebug-2.2.5/xdebug.c:1437
#118 0x00007fcbd0de94ca in zend_do_fcall_common_helper_SPEC ()
#119 0x00007fcbd0d7d198 in execute_ex ()
#120 0x00007fcbd0d2ef09 in dtrace_execute_ex ()
#121 0x00007fcbc6373ebc in xdebug_execute_ex (execute_data=0x7fcbd0a8e320) at /tmp/xdebug-2.2.5/xdebug.c:1437
#122 0x00007fcbd0d41f2b in zend_execute_scripts ()
#123 0x00007fcbd0cdd352 in php_execute_script ()
#124 0x00007fcbd0ba10eb in main ()
(gdb) 
```

**Comment by andresgutierrez** [comment]
This is happening reading an annotation, can you check what annotation is causing this?

**Comment by patrick-zippenfenig** [comment]
Related: https://github.com/phalcon/cphalcon/issues/10140#issuecomment-99930966

**Comment by virgofx** [comment]
I'm trying to reproduce the issue and it appears randomly on our test application ... in general, we use the annotations memory adapter (files in production) for our model metadata as described here: 

http://blog.phalconphp.com/post/47471246411/tutorial-creating-a-custom-models-initializer

We did extend the functionality to provide a few additional event callbacks. I'll try to provide more info -- I'm going in order trying to isolate all these segfaults with proper gdb trace enabled.

**Comment by patrick-zippenfenig** [comment]
Could you run phalcons unit-tests?
````
curl -sS https://getcomposer.org/installer | php
php composer.phar install
gdb --args php ./unit-tests/ci/phpunit.php --debug -c unit-tests/phpunit.xml --testsuite=stable
(gdb) run
````
I most likely can reproduce the same behaviour:
````
Starting test 'AnnotationsAdaptersTest::testMemoryAdapter'.

Program received signal SIGSEGV, Segmentation fault.
0x0833c3ba in ?? ()
(gdb) bt ful
#0  0x0833c3ba in ?? ()
No symbol table info available.
#1  0xb1256e98 in phannot_internal_parse_annotations (result=0xbfffa550, comment=0xaed49bc4, file_path=0xaeeb2540, line=0xaef2c66c, error_msg=0xbfffa53c)
    at /var/www/cphalcon/ext/phalcon/annotations/parser.c:1441
        error = 0xbfffa548 "X\247\377\277\310t\354\260\330\310\362\256ě\324\256@%\353\256l\306\362\256g\314-\261\v"
        state = 0x8a28068
        token = {value = 0x8b0b9f0 "\001", opcode = -1238750784, len = -1359820584}
        scanner_status = -1073765028
        status = 0
        start_lines = 2
        error_length = -1326848344
        parser_status = 0x0
        phannot_parser = 0x4
        processed_comment = {value = {lval = -1219157972, dval = 1.5196517201465879e-314, str = {val = 0xb755202c "", len = 0}, ht = 0xb755202c, obj = {
              handle = 3075809324, handlers = 0x0}, ast = 0xb755202c}, refcount__gc = 149583280, type = 6 '\006', is_ref__gc = 0 '\000'}
#2  0xb125684c in phannot_parse_annotations (result=0xaef2c8d8, comment=0xaed49bc4, file_path=0xaeeb2540, line=0xaef2c66c)
    at /var/www/cphalcon/ext/phalcon/annotations/parser.c:1305
        error_msg = 0x0
#3  0xb0ec74c8 in zim_Phalcon_Annotations_Reader_parse (ht=1, return_value=0xaef2f3a8, return_value_ptr=0xbfffaaec, this_ptr=0xaef2f4c8, return_value_used=1)
    at /var/www/cphalcon/ext/phalcon/annotations/reader.zep.c:97
        _8 = 0xaed3461c
        _14 = 0x8b08834
        _7 = 0x8e6b91c
        _13 = 0xb629ef58
        _0 = 0x0
        _1 = 0x0
        _3 = 0x0
        _5 = 0x0
        _6 = 0x0
_12 = 0x0
        line = 1
        ZEPHIR_LAST_CALL_STATUS = 0
        className_param = 0xaef2f68c
        annotations = 0xaef2fdb4
        reflection = 0xaef2f2d8
        comment = 0xaed49bc4
        properties = 0xaef404e4
        methods = 0x0
        property = 0xaef36430
        method = 0x0
        classAnnotations = 0xaef2f8b4
        annotationsProperties = 0xaef2c9cc
        propertyAnnotations = 0xaef2c8d8
        annotationsMethods = 0x0
        methodAnnotations = 0x0
        _2 = 0xaeeb2540
        _4 = 0xaef2fe90
        _9 = 0x8e6b928
        _10 = 0xaef2c66c
        _11 = 0xaef36570
        _15 = 0xbfffa850
        className = 0xaef2f68c
````

**Comment by virgofx** [comment]
Yep -- same error:

```
Starting test 'AnnotationsAdaptersTest::testMemoryAdapter'.
.
Starting test 'AnnotationsAdaptersTest::testFilesAdapter'.

Program received signal SIGSEGV, Segmentation fault.
_zend_mm_free_int (heap=0x555555bc7ef0, p=0x7fffdc902b40) at /usr/src/debug/php-5.6.8/Zend/zend_alloc.c:2104
2104            if (ZEND_MM_IS_FREE_BLOCK(next_block))
```

```
(gdb) bt
#0  _zend_mm_free_int (heap=0x555555bc7ef0, p=0x7fffdc902b40) at /usr/src/debug/php-5.6.8/Zend/zend_alloc.c:2104
#1  0x00007fffe4a3be3d in phannot_internal_parse_annotations.isra.98 () from /usr/lib64/php/modules/phalcon.so
#2  0x00007fffe4c15bc7 in zim_Phalcon_Annotations_Reader_parse () from /usr/lib64/php/modules/phalcon.so
#3  0x00005555557a352b in dtrace_execute_internal (execute_data_ptr=<optimized out>, fci=<optimized out>, return_value_used=<optimized out>)
    at /usr/src/debug/php-5.6.8/Zend/zend_dtrace.c:97
#4  0x00007fffed2f4936 in xdebug_execute_internal (current_execute_data=0x7fffffff8810, fci=0x7fffffff8980, return_value_used=1) at /var/tmp/xdebug/xdebug.c:1553
#5  0x00007fffe4a29740 in zephir_call_function_opt () from /usr/lib64/php/modules/phalcon.so
#6  0x00007fffe4a572df in zephir_call_user_function () from /usr/lib64/php/modules/phalcon.so
#7  0x00007fffe4a57514 in zephir_call_class_method_aparams () from /usr/lib64/php/modules/phalcon.so
#8  0x00007fffe4adabb9 in zim_Phalcon_Annotations_Adapter_get () from /usr/lib64/php/modules/phalcon.so
#9  0x00005555557a352b in dtrace_execute_internal (execute_data_ptr=<optimized out>, fci=<optimized out>, return_value_used=<optimized out>)
    at /usr/src/debug/php-5.6.8/Zend/zend_dtrace.c:97
#10 0x00007fffed2f4936 in xdebug_execute_internal (current_execute_data=0x7ffff7fa54d0, fci=0x0, return_value_used=1) at /var/tmp/xdebug/xdebug.c:1553
#11 0x000055555585d468 in zend_do_fcall_common_helper_SPEC (execute_data=<optimized out>) at /usr/src/debug/php-5.6.8/Zend/zend_vm_execute.h:560
#12 0x00005555557f1698 in execute_ex (execute_data=0x7ffff7fa54d0) at /usr/src/debug/php-5.6.8/Zend/zend_vm_execute.h:363
#13 0x00005555557a3409 in dtrace_execute_ex (execute_data=<optimized out>) at /usr/src/debug/php-5.6.8/Zend/zend_dtrace.c:73
#14 0x00007fffed2f3ebc in xdebug_execute_ex (execute_data=0x7ffff7fa54d0) at /var/tmp/xdebug/xdebug.c:1439
#15 0x00005555557a51f3 in zend_call_function (fci=fci@entry=0x7fffffff9290, fci_cache=<optimized out>, fci_cache@entry=0x7fffffff9260)
    at /usr/src/debug/php-5.6.8/Zend/zend_execute_API.c:829
#16 0x00005555556a79d6 in zim_reflection_method_invokeArgs (ht=<optimized out>, return_value=0x555556a63c68, return_value_ptr=<optimized out>, this_ptr=<optimized out>, 
    return_value_used=<optimized out>) at /usr/src/debug/php-5.6.8/ext/reflection/php_reflection.c:3045
#17 0x00005555557a352b in dtrace_execute_internal (execute_data_ptr=<optimized out>, fci=<optimized out>, return_value_used=<optimized out>)
    at /usr/src/debug/php-5.6.8/Zend/zend_dtrace.c:97
#18 0x00007fffed2f4936 in xdebug_execute_internal (current_execute_data=0x7ffff7fa5338, fci=0x0, return_value_used=1) at /var/tmp/xdebug/xdebug.c:1553
#19 0x000055555585d468 in zend_do_fcall_common_helper_SPEC (execute_data=<optimized out>) at /usr/src/debug/php-5.6.8/Zend/zend_vm_execute.h:560
#20 0x00005555557f1698 in execute_ex (execute_data=0x7ffff7fa5338) at /usr/src/debug/php-5.6.8/Zend/zend_vm_execute.h:363
#21 0x00005555557a3409 in dtrace_execute_ex (execute_data=<optimized out>) at /usr/src/debug/php-5.6.8/Zend/zend_dtrace.c:73
#22 0x00007fffed2f3ebc in xdebug_execute_ex (execute_data=0x7ffff7fa5338) at /var/tmp/xdebug/xdebug.c:1439
#23 0x000055555585d9ca in zend_do_fcall_common_helper_SPEC (execute_data=<optimized out>) at /usr/src/debug/php-5.6.8/Zend/zend_vm_execute.h:592
#24 0x00005555557f1698 in execute_ex (execute_data=0x7ffff7fa51c8) at /usr/src/debug/php-5.6.8/Zend/zend_vm_execute.h:363
#25 0x00005555557a3409 in dtrace_execute_ex (execute_data=<optimized out>) at /usr/src/debug/php-5.6.8/Zend/zend_dtrace.c:73
#26 0x00007fffed2f3ebc in xdebug_execute_ex (execute_data=0x7ffff7fa51c8) at /var/tmp/xdebug/xdebug.c:1439
#27 0x000055555585d9ca in zend_do_fcall_common_helper_SPEC (execute_data=<optimized out>) at /usr/src/debug/php-5.6.8/Zend/zend_vm_execute.h:592
#28 0x00005555557f1698 in execute_ex (execute_data=0x7ffff7fa4f58) at /usr/src/debug/php-5.6.8/Zend/zend_vm_execute.h:363
#29 0x00005555557a3409 in dtrace_execute_ex (execute_data=<optimized out>) at /usr/src/debug/php-5.6.8/Zend/zend_dtrace.c:73
#30 0x00007fffed2f3ebc in xdebug_execute_ex (execute_data=0x7ffff7fa4f58) at /var/tmp/xdebug/xdebug.c:1439
```

**Comment by andresgutierrez** [comment]
This is now fixed in 2.0.x, could you please try again using this branch?

**Comment by virgofx** [comment]
I've confirmed the error is **not** happening in the unit-tests. 

Since I also was able to reproduce this intermittently using our internal dev application, I'm going to run using latest 2.0.x all day just to make sure I don't see this as well and then confirm later tonight/tomorrow.

**Comment by patrick-zippenfenig** [comment]
:+1:  works

**Comment by andresgutierrez** [comment]
@virgofx Could you please this if it is fixed?

**Comment by virgofx** [comment]
@andresgutierrez Sorry for the delay ... was testing using the latest changes this week in our main app environment and I didn't notice anything specific that would lead me to believe the issue is still there. I'm trying to isolate a few other issues which I believe are un-related. Marking as fixed.
