### ISSUE TITLE
Possible bug in volt macro?

### ISSUE THREAD

**Issue by aderbas** [phalcon/cphalcon#11781]
I created some "components" using macros in the template volt model. But I do not understand what the problem is. I created a simple project "store" using Phalcon tools and create a simple macro in volt file like that

view/component/foo.volt
```
{%- macro foo(bar='') %}
    <h1>{{ bar }}</h1>
{%- endmacro %}
```

In index.volt I try
```
{{ partial('correct/path/to/macro/foo')}}
{{ foo('My text here') }}
```

This render: `<h1>M</h1>` it should be: `<h1>My text here</h1>`

Linux Mint Rafaela 17.2 Cinnamon / Apache 2 / PHP 5.5.9 / Phalcon 2.0.11

**Comment by sergeyklay** [comment]
Fixed in the 2.0.x branch

https://github.com/phalcon/cphalcon/issues/11745
https://github.com/phalcon/cphalcon/issues/11771

**Comment by aderbas** [comment]
Can you push the fix?

**Comment by sergeyklay** [comment]
You have to use the `2.0.x` branch (compile Phalcon from source) or wait few days in order to use released version.

**Comment by aderbas** [comment]
Yep, I did it but I installed Phalcon before using the PPA. I did clone 2.0.x branch follow the steps but I'm not sure it worked because the problem persists.

**Comment by sergeyklay** [comment]
@aderbas As you can see https://github.com/phalcon/cphalcon/pull/11765 all tests passed

**Comment by aderbas** [comment]
Ok, I try complete remove Phalcon and compile 2.0.x again. Thks.

**Comment by Jurigag** [comment]
You don't need to remove. Just clone 2.0.x, compile it and restart apache/php-fpm

**Comment by aderbas** [comment]
Yes, I've do it but nothing changed. After compile the branch in `phpinfo()` continues 2.0.11, is that right?

**Comment by Jurigag** [comment]
Yes, it's right. Yo sure you restarted apache and php-fpm and **cloned 2.0.x BRANCH, not MASTER** ?

**Comment by aderbas** [comment]
Yes, I'm restart apache, php-fpm did not work, finally I did reboot the SO. I think it's a problem with the OS, so I will try to completely remove the Phalcon and start from the beginning = /

**Comment by Jurigag** [comment]
But you sure you cloned 2.0.x, not master ?

**Comment by aderbas** [comment]
Yep, 2.0.x, I'm not in the pc when you get will try again before removing. Thank you.

**Comment by aderbas** [comment]
Guys, not work. I do not know what I'm doing wrong.

![2.0.x](http://i.imgur.com/Inw5Nxn.png)

![Installed](http://i.imgur.com/F1r9W5E.png)

![PHP info](http://i.imgur.com/vYEhXGm.png)

I restart everything but bug persist =(

**Comment by aderbas** [comment]
Update guys, I installed 2.1.x and works. Waiting for v 2.0.12. Thks
