### ISSUE TITLE
Are there any known issues with Phalcon\Validation\Validator\Uniqueness?

### ISSUE THREAD

**Issue by garyrutland** [phalcon/cphalcon#12554]
Hi,

I've been using this validator for a while now but recently updated from `3.0.0` to `3.0.3` and since then I've been getting an error stating `At least one model is required to build the query`.

Below is a sample of the code I am trying to run, is there any reason why this wouldn't work anymore?
The class this is taken from is extending `Phalcon\Forms\Form`.

    <?php
    
    use App\Models\User;
    use Phalcon\Forms;
    use Phalcon\Validation\Validator;
    
    $email = new Forms\Element\Email('email');
    $email->setLabel('Email');
    $email->setFilters([
        'email',
        'striptags',
        'string',
        'trim',
    ]);
    $email->addValidators([
        new Validator\PresenceOf([
            'message' => 'Email is required',
        ]),
        new Validator\Email(),
        new Validator\Uniqueness([
            'model'   => new User(),
            'message' => 'Email already exists',
        ]),
    ]);
    $this->add($email);

Thanks,
Gary

**Comment by Jurigag** [comment]
I guess this - https://github.com/phalcon/cphalcon/commit/c505c6896bf602985d075f6f1da221031f22e57a broke soemthing

**Comment by garyrutland** [comment]
I can definitely try.

Is there any documentation on how to do this?  
(I haven't had to do it before)

**Comment by Jurigag** [comment]
https://github.com/phalcon/cphalcon/tree/master/tests/unit just look in other tests here

**Comment by garyrutland** [comment]
Ok, shall try and do so in a couple/few of hours.

**Comment by Jurigag** [comment]
This is really

https://github.com/phalcon/cphalcon/blob/v3.0.3/phalcon/mvc/model.zep#L1181  using from method
https://github.com/phalcon/cphalcon/blob/v3.0.3/phalcon/mvc/model/query/builder.zep#L385  which sets _models property
https://github.com/phalcon/cphalcon/blob/v3.0.3/phalcon/mvc/model/query/builder.zep#L1045  but here it's somehow hitting exception anyway like those conditions are true somehow. Any idea @andresgutierrez @sergeyklay

**Comment by stamster** [comment]
This should be fixed ASAP, as 3.0.x has been labelled LTS.

**Comment by Jurigag** [comment]
Yea but why it's happening in first place?

**Comment by garyrutland** [comment]
Sorry I haven't added a test in for this yet, I've been struggling to find the time.  
I have, however, pledged what I can (for now) to try and help you out.  
I know it's not much in the grand scheme of things but I hope to up it in the future.

**Comment by Jurigag** [comment]
Does anyone has code to reproduce this?

**Comment by sergeyklay** [comment]
@garyrutland Could you please ping back for now :) Is issue still present. Probably we need a small working script to reproduce the issue if any

**Comment by garyrutland** [comment]
I'm now using version `3.0.4` and don't seem to be having the same issue.

**Comment by sergeyklay** [comment]
Thank you
