### ISSUE TITLE
trap invalid opcode .... in phalcon.so

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#13143]
I'm trying to run a phalcon docker build on coreOS using docker swarm.
My dockerfile is based from phalconphp/php:alpine-3-php7

Locally the image works fine (Mac).

I'm seeing the following errors: 

```
[02-Nov-2017 18:39:12] WARNING: [pool www] child 86 exited on signal 4 (SIGILL - core dumped) after 315.152352 seconds from start
```

```
[522081.446459] traps: php-fpm[18560] trap invalid opcode ip:7fd1ddb83590 sp:7ffcd30b2b20 error:0 in phalcon.so[7fd1dd857000+686000]

```

```
/ # php --ri phalcon

phalcon


Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.2.2
Build Date => Aug 18 2017 13:56:35
Powered by Zephir => Version 0.9.9-868cb1f92b

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.disable_assign_setters => Off => Off
```
```
/ # php -v
PHP 7.1.5 (cli) (built: May 13 2017 10:49:18) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.5, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.3, Copyright (c) 2002-2017, by Derick Rethans
```

**Comment by ruudboon** [comment]
Upgraded to php 7.1.11 and phalcon 3.2.4, still same issue.

**Comment by ruudboon** [comment]
Pin pointed the issue to the router.
```
<?php
$router = new Phalcon\Mvc\Router();

```
```
/project/application/public # php index.php 
Illegal instruction (core dumped)
```

**Comment by ruudboon** [comment]
I think the problem is that I compile the docker image on my Mac and then push the image to my local repository. My staging env pull the image from the repository and tries to run it. 
Looks like phalcon is linking to some host dependencies because when I rebuild phalcon inside the container on my staging environment it works. 

I'm not a c++ expert so can't really tell what's happening. But I do think it should be possible to build the image locally and push it to the repository to run in on different docker host system. Please correct me if I'm wrong.

**Comment by sergeyklay** [comment]
Could you please provide the steps to reproduce?

**Comment by h1kkan** [comment]
Hi guys, i've same issue, and find out root cause of it :) 

it's caused by `-mtune=native` gcc build flag

I've builded docker image on AMD based host, tested it on it - and all was ok, and then we deploy it to AWS (Intel Xeon based EC2 instance) and get this errors:

```
[690962.001987] traps: php-fpm7.1[24545] trap invalid opcode ip:7f2a30d105d4 sp:7ffc2287e718 error:0 in phalcon.so[7f2a30c86000+476000]
[690963.423646] traps: php-fpm7.1[24562] trap invalid opcode ip:7fdc171105d4 sp:7fff597581d8 error:0 in phalcon.so[7fdc17086000+476000]
[690965.825258] traps: php-fpm7.1[24566] trap invalid opcode ip:7fb0017105d4 sp:7fffe7e133c8 error:0 in phalcon.so[7fb001686000+476000]
[690969.176541] traps: php-fpm7.1[24570] trap invalid opcode ip:7f9081b105d4 sp:7ffd2ad4c538 error:0 in phalcon.so[7f9081a86000+476000]
```

After rebuild on Intel Xeon based host (in my case - it was hetzner dedicated server), then deployed it to same EC2 instance - and issue was resolved :)

**Comment by sergeyklay** [comment]
@ruudboon, @h1kkan Could you please remove **`-mtune=native`** from the `build/install` script and try reinstall Phalcon?

Refs: https://github.com/phalcon/php-zephir-parser/issues/33

**Comment by ruudboon** [comment]
@sergeyklay Looks like this resolve the issue. Thnx

**Comment by ruudboon** [comment]
I think there is something more happening. When creating a phalcon docker build on my Mac (Intel Core i7) I'm unable to run this container on my server with Xeon processor. 
I tried removing -mtune=native but doesn't solve the issue. Building the same image on the Xeon environment works fine.

**Comment by ruudboon** [comment]
This topic could be related: https://forum.phalconphp.com/discussion/19297/502-bad-gateway-on-docker-nginx

**Comment by ruudboon** [comment]
I've tested this on a few systems. On most systems it works. I now have 2 failing places. The VPS where it started with and an old Mac Pro from 2009 with an XEON cpu.

**Comment by ruudboon** [comment]
After reading [this](http://sdf.org/~riley/blog/2014/10/30/march-mtune/) is solved the issue.
The -march takes precedence in relation with -mtune. Wil create a pull for that.

**Comment by niden** [comment]
This has been addressed
