### ISSUE TITLE
The record doesn't have a valid data snapshot in 1.3.0

### ISSUE THREAD

**Issue by MaksSlesarenko** [phalcon/cphalcon#1867]
All models use dynamic update, but periodically error message appears
Same problem was in previous versions.

According to doc http://docs.phalconphp.com/en/1.3.0/reference/models-cache.html#overriding-find-findfirst you may override find and findFirst method. As I understand problem appears when save failed and refresh is performed, which also uses those methods.

**Comment by jamm** [comment]
100% reproducible, just call getChangedFields() for object not yet saved or loaded from db (newly created).

**Comment by marcTJP** [comment]
I've tried getChangedFields() with Create and Update steps posted by Dusan but it just returns 'The record doesn't have a valid data snapshot'.

**Comment by msty** [comment]
To fix the 'The record doesn't have a valid data snapshot' you need to do one of the two things:
1. Fetch record from database, example: $model = MyModel::findFirst($id);
2. Explicitly set snapshot data when you need it: $myModel->setSnapshotData($myModel->toArray());

The bug is that setSnapshotData() is called internally only when you fetch data from database, and is NOT called when you save data or simply assign fields. If it's not a bug, it needs to be at least documented.

**Comment by web777** [comment]
@msty But Phalcon dont have `afterFetch` event for autofix

**Comment by web777** [comment]
@msty thanks for fix, maybe in version 2 will correct

**Comment by daveamol** [comment]
I'm having the same issue when fetching multiple records in a loop using findFirst and then later updating them again in another loop based on some conditions. @msty the fix works but can you give me some more insight on why it works ?

**Comment by goke-epapa** [comment]
This issues seems to occur when you call.
```php
$model->save(); 
```
instead of

```php
$model->update();
```
Changing to update instead of save fixed this issue for me.

**Comment by manish-ga** [comment]
create, update does NOT work.

**Comment by jturbide** [comment]
is there a better solution than mine? ty

    public function beforeCreate() {
        $this->setSnapshotData($this->toArray());
    }

**Comment by andresgutierrez** [comment]
Are you using Phalcon >= 2.0.7?

**Comment by jturbide** [comment]
Yes the bleeding edge ;)

**Comment by od3n** [comment]
+1 same here. Currently use jturbide's solution

**Comment by thepatron** [comment]
+ 1 same here on 2.0.7.

**Comment by Zaszczyk** [comment]
+1 same here on 2.1.x beta

**Comment by ruudboon** [comment]
Seeing this issue also on 2.0.8. Any workarounds in the meantime?

**Comment by zhudonghe** [comment]
+1 same here on 2.09 on centOS

In my code, getSnapshotData() & hasChanged('startDate') are invoked in the afterUpdate() in the model.

When I first create[$object->create()] this model object, then update this object. The issue emerge.

But after the creation. If getting the object again [$object = Model::findFIrst($object->ID]. then update the object. There was no such issue. 

BTW.   Only $object->refresh() could not fix the issue.

**Comment by ignaciovazquez** [comment]
In my case it works fine on update, it just fails while creating new records. 

I'd like to be able to get the initial data entered in the model via getChangedFields() and save it in an audit log.

**Comment by sergeyklay** [comment]
The 1.3.x version is no longer supported.

**Comment by ignaciovazquez** [comment]
It's happening in 2.0.8.

Should getChangedFields work on newly created records as well?

**Comment by sergeyklay** [comment]
Create separated issue please

**Comment by tegaphilip** [comment]
@ignaciovazquez when saving, are you saving a single model or a model and its related records?

**Comment by ignaciovazquez** [comment]
@tegaphilip  It was a single model. I solved this some time ago, but I don't remember exactly what the fix was. It had to do with saving the object twice in the same script.

**Comment by tegaphilip** [comment]
@ignaciovazquez you are right. i solved mine just now. was saving the object twice. first on its own , then saving it with its related model. separated the saves and it was fixed. thanks.

**Comment by ignaciovazquez** [comment]
I'm glad I could help.

I still think it's a bug. Saving it twice shouldn't be causing this issue.

**Comment by jeiel** [comment]
I have the same problem in 2.01r

**Comment by pantaovay** [comment]
+1 2.0.8

**Comment by hakimio** [comment]
The issue is still present in 2.0.10. DusanBrejka posted a detailed explanation for the issue with code example. There shouldn't be any problem reproducing it.

**Comment by sergeyklay** [comment]
@hakimio Could you please open new issue with script to reproduce?

**Comment by david-duncan** [comment]
2.0.13

1) Create with transaction
2) Later update in same transaction
3) With hasChanged('fieldName') in beforeValidationOnUpdate hook, it will `throw Internal Error: The record doesn't have a valid data snapshot`
